ingress-nginx:
  controller:
    service:
      externalTrafficPolicy: Local
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
        service.beta.kubernetes.io/azure-load-balancer-internal: "true" 
        service.beta.kubernetes.io/azure-pls-create: "true"
        service.beta.kubernetes.io/azure-pls-name: AksDemoPls 
        service.beta.kubernetes.io/azure-pls-ip-configuration-subnet: "PLSSubnet"
    electionID: ingress-controller-pls
    ingressClassResource:
      name: nginx-pls
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-pls"
    config:
      use-forwarded-headers: "true"